# Generated by Django 5.2 on 2025-05-11 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('barcode_no', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_detail', models.CharField(max_length=255)),
                ('product_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('product_expiry', models.DateField()),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('archived', 'Archived'), ('low_stock', 'Low Stock'), ('expiring_soon', 'Expiring Soon')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'tbl_notification',
            },
        ),
        migrations.CreateModel(
            name='Distrib',
            fields=[
                ('distrib_id', models.AutoField(primary_key=True, serialize=False)),
                ('distrib_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'tbl_distrib',
            },
        ),
    ]
