# Generated by Django 5.1.6 on 2025-05-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_alter_user_contact_notification_distrib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode_no',
            field=models.CharField(max_length=20),
        ),
    ]
